name: Build Release (AAB + APK) - Signed

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: dzfreelance
      KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      NAME: "Lahmar Walid"
      ORG: "FreelanceDZ"
      CITY: "Oran"
      STATE: "Oran"
      COUNTRY: "DZ"
      EMAIL: "walidorani5001@gmail.com"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Run flutter pub get
        run: flutter pub get

      - name: Generate keystore
        run: |
          mkdir -p android/app
          keytool -genkeypair \
            -alias "$KEY_ALIAS" \
            -keyalg RSA -keysize 2048 \
            -storetype PKCS12 \
            -keystore android/app/dzfreelance.keystore \
            -storepass "$STORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -validity 10000 \
            -dname "CN=${NAME}, OU=${ORG}, O=${ORG}, L=${CITY}, ST=${STATE}, C=${COUNTRY}, EMAILADDRESS=${EMAIL}"

      - name: Create key.properties
        run: |
          cat > android/key.properties <<EOF
storePassword=${{ secrets.KEYSTORE_PASSWORD }}
keyPassword=${{ secrets.KEYSTORE_PASSWORD }}
keyAlias=dzfreelance
storeFile=dzfreelance.keystore
EOF

      - name: Build app bundle (AAB)
        run: flutter build appbundle --release

      - name: Build APK
        run: flutter build apk --release

      - name: Upload signed AAB and APK
        uses: actions/upload-artifact@v4
        with:
          name: dz-freelance-release
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
            android/app/dzfreelance.keystore
            android/key.properties
